chartsPath: {{cookiecutter.helm_charts_directory}}\

repositories:
  hobops: { url: https://hobops-helm-charts.storage.googleapis.com }
  ingress-nginx: { url: https://kubernetes.github.io/ingress-nginx }
  jetstack: { url: https://charts.jetstack.io }
  bitnami: { url: https://charts.bitnami.com/bitnami }

# Add new repositories in alphabetical order (Sublime/PyCharm can the lines)

charts:
  # Infrastructure
  cert-manager-clusterissuer: { chart: 'hobops/cert-manager-clusterissuer', version: '1.0.1', needs: [cert-manager], disableValidation: true }
  cert-manager: { chart: 'jetstack/cert-manager', version: 'v1.9.1' }
  ingress-nginx: { chart: 'ingress-nginx/ingress-nginx', version: '4.2.5' }
  # Add new infrastructure charts in alphabetical order (Sublime/PyCharm can sort lines)
  # Apps
  nginx: { chart: 'bitnami/nginx', version: '13.2.4' }
  redis: { chart: 'bitnami/redis', version: '17.1.4' }
  # Add new charts in alphabetical order (Sublime/PyCharm can sort lines)