# Load common sections for clusters
{{ "{{" }} readFile "include/common_clusters.yaml" {{ "}}" }}

# Load releases
{{ "{{" }} readFile "rendered/releases.yaml.gotmpl" {{ "}}" }}

# Load clusters
{{ "{{" }} readFile "clusters/index.yaml" {{ "}}" }}
